# Generated by Django 6.0.3 on 2026-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
