# Generated by Django 6.0.3 on 2026-04-01 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_fileversion_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together={('file', 'shared_with')},
        ),
    ]
