# Generated by Django 6.0.3 on 2026-03-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Audit Logs'},
        ),
    ]
