# Generated by Django 6.0.3 on 2026-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='checksum',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
